services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bikrant-network
    ports:
      - "5432:5432"

networks:
  bikrant-network:
    driver: bridge

volumes:
  postgres-data:
