name: Portfolio Website Build and Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    name: Build and Archive Web Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build static website
        run: bun run build

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "release.zip"

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-archive
          path: release.zip

  release:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: build-and-archive

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-archive

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx semantic-release
